import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Learning With Firdaus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* <div className="flex h-screen">
          <Sidebar />
          <div className="flex flex-col flex-1 ml-64">
            <Navbar />
            <main className="p-8 flex-1 overflow-auto">{children}</main>
          </div>
        </div> */}
        {children}
      </body>
    </html>
  );
}
